// Generated by CoffeeScript 1.8.0
(function() {
  return $('.del').click(function(event) {
    var b, self;
    self = $(this);
    b = confirm('你确定要删除吗？');
    if (!b) {
      return;
    }
    return $.ajax({
      type: 'delete',
      url: "/movies/" + (self.data('id')),
      success: function() {
        return self.parents('tr').remove();
      },
      error: function(error) {
        return alert(error);
      }
    });
  });
})();
